### ISSUE TITLE
Cannot import name 'main' from 'pyamiimage.pyamiimage'

### ISSUE THREAD

**Issue by anuvc** [petermr/pyamiimage#3]
Specs:
OS: Windows 10
Python: 3.9

After installing `pyamiimage` using pip:
```
pip install pyamiimage
```
Running `pyamiimage` 
```
PS C:\Users\chakr> pyamiimage
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\chakr\AppData\Roaming\Python\Python39\Scripts\pyamiimage.exe\__main__.py", line 4, in <module>
ImportError: cannot import name 'main' from 'pyamiimage.pyamiimage' (C:\Users\chakr\projects\pyamiimage\pyamiimage\__init__.py)
```

I have `pyamiimage` repository in my PC. I also have added the `pyamiimage` to $PYTHONPATH variable so it is accessible from as a package name during imports.

**Comment by anuvc** [comment]
Imports have been solved in `pyamiimage v0.0.12` 
If you are having this issue consider upgrading your pyamiimage using:
`pip install --upgrade pyamiimage`
